package main

import (
	"fmt"
	"log"
	"os"
	"reflect"
	"strings"
	"time"
)

type Right struct {
	Section     string `json:"section"`
	User        string `json:"user"`
	Collection  string `json:"collection"`
	Permissions string `json:"permissions"`
}

type Symlink struct {
	Source string `json:"source"`
	User   string `json:"user"`
}

func generateRightsFileContent(rights []Right) (string, error) {
	var builder strings.Builder

	builder.WriteString("# Generated by Radicale HTTP Controller\n")
	builder.WriteString(fmt.Sprintf(
		"# Timestamp: %s\n\n",
		time.Now().Format(time.RFC3339),
	))

	for _, right := range rights {
		if right.Section == "" {
			log.Printf(
				"WARN: Skipping right rule with empty section: %+v",
				right,
			)
			continue
		}
		builder.WriteString(fmt.Sprintf("[%s]\n", right.Section))
		if right.User != "" {
			builder.WriteString(fmt.Sprintf("user: %s\n", right.User))
		}
		builder.WriteString(fmt.Sprintf("collection: %s\n", right.Collection))
		if right.Permissions != "" {
			builder.WriteString(fmt.Sprintf(
				"permissions: %s\n",
				right.Permissions,
			))
		}
		builder.WriteString("\n")
	}

	return builder.String(), nil
}

func writeToFile(filePath, content string) error {
	log.Printf("Writing configuration to %s", filePath)
	// Attempt to read existing content to compare
	existingContent, err := os.ReadFile(filePath)
	if err == nil && string(existingContent) == content {
		log.Printf("Content for %s is unchanged. Skipping write.", filePath)
		return nil // No error, just skip writing
	} else if err != nil && !os.IsNotExist(err) {
		// Log error if it's something other than the file not existing yet
		log.Printf(
			"WARN: Could not read existing file %s to compare: %v",
			filePath,
			err,
		)
	}

	// Write the new content
	err = os.WriteFile(filePath, []byte(content), 0644)
	if err != nil {
		return fmt.Errorf("failed to write to file %s: %w", filePath, err)
	}
	log.Printf("Successfully wrote configuration to %s", filePath)
	return nil
}

func runController() {
	cfg := loadConfiguration()

	ticker := time.NewTicker(cfg.PollInterval)
	defer ticker.Stop()

	log.Println("Performing initial configuration fetch...")
	processConfiguration(cfg)

	for range ticker.C {
		processConfiguration(cfg)
	}
}

func processConfiguration(cfg *ControllerConfig) {
	newConfig, err := fetchConfig(cfg)
	if err != nil {
		log.Printf("ERROR: Failed to fetch or parse configuration: %v", err)
		return
	}

	if currentConfig != nil && reflect.DeepEqual(newConfig, currentConfig) {
		log.Println("Configuration hasn't changed. No action needed.")
		return
	}

	log.Println("Configuration change detected. Applying updates...")

	rightsContent, err := generateRightsFileContent(newConfig.Rights)
	if err != nil {
		log.Printf("ERROR: Failed to generate rights file content: %v", err)
	} else {
		err = writeToFile(cfg.RightsFilePath, rightsContent)
		if err != nil {
			log.Printf("ERROR: Failed to write rights file: %v", err)
		}
	}

	err = manageSymlinks(newConfig.Symlinks, cfg.RadicaleStoragePath)
	if err != nil {
		log.Printf("ERROR: Failed during symlink processing: %v", err)
	}

	log.Println("Configuration update applied.")
	currentConfig = newConfig
}
