package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"time"

	v1 "k8s.io/api/core/v1"
	k8serrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/client-go/util/retry"
)

type Right struct {
	Section     string `json:"section"`
	User        string `json:"user"`
	Collection  string `json:"collection"`
	Permissions string `json:"permissions"`
}

type Symlink struct {
	Source string `json:"source"`
	User   string `json:"user"`
}

func generateRightsFileContent(rights []Right) (string, error) {
	var builder strings.Builder

	builder.WriteString("# Generated by Radicale Controller\n")
	builder.WriteString(fmt.Sprintf(
		"# Timestamp: %s\n\n",
		time.Now().Format(time.RFC3339),
	))

	for _, right := range rights {
		if right.Section == "" {
			log.Printf(
				"WARN: Skipping right rule with empty section: %+v",
				right,
			)
			continue
		}
		builder.WriteString(fmt.Sprintf("[%s]\n", right.Section))
		if right.User != "" {
			builder.WriteString(fmt.Sprintf("user: %s\n", right.User))
		}
		builder.WriteString(fmt.Sprintf("collection: %s\n", right.Collection))
		if right.Permissions != "" {
			builder.WriteString(fmt.Sprintf(
				"permissions: %s\n",
				right.Permissions,
			))
		}
		builder.WriteString("\n")
	}

	return builder.String(), nil
}

func writeToFile(filePath, content string) error {
	log.Printf("Writing configuration to %s", filePath)
	existingContent, err := os.ReadFile(filePath)
	if err == nil && string(existingContent) == content {
		log.Printf("Content for %s is unchanged. Skipping write.", filePath)
		return nil
	} else if err != nil && !os.IsNotExist(err) {
		log.Printf(
			"WARN: Could not read existing file %s to compare: %v",
			filePath,
			err,
		)
	}

	// Ensure directory exists
	dirPath := filepath.Dir(filePath)
	if err := os.MkdirAll(dirPath, 0755); err != nil {
		return fmt.Errorf("failed to create directory %s: %w", dirPath, err)
	}

	err = os.WriteFile(filePath, []byte(content), 0644)
	if err != nil {
		return fmt.Errorf("failed to write to file %s: %w", filePath, err)
	}
	log.Printf("Successfully wrote configuration to %s", filePath)
	return nil
}

func writeRightsToConfigMap(ctx context.Context, cfg *ControllerConfig, content string) error {
	if !cfg.IsInKubernetes || cfg.KubeClient == nil || cfg.RightsConfigMapName == "" {
		return fmt.Errorf("cannot write to ConfigMap, Kubernetes integration not configured properly")
	}

	cmClient := cfg.KubeClient.CoreV1().ConfigMaps(cfg.RightsConfigMapNamespace)
	configMapName := cfg.RightsConfigMapName
	configMapKey := cfg.RightsConfigMapKey

	log.Printf("Attempting to update ConfigMap '%s/%s' with key '%s'", cfg.RightsConfigMapNamespace, configMapName, configMapKey)

	retryErr := retry.RetryOnConflict(retry.DefaultRetry, func() error {
		cm, err := cmClient.Get(ctx, configMapName, metav1.GetOptions{})
		if err != nil {
			if k8serrors.IsNotFound(err) {
				log.Printf("ConfigMap '%s' not found, creating...", configMapName)
				newCm := &v1.ConfigMap{
					ObjectMeta: metav1.ObjectMeta{
						Name:      configMapName,
						Namespace: cfg.RightsConfigMapNamespace,
					},
					Data: map[string]string{
						configMapKey: content,
					},
				}
				_, createErr := cmClient.Create(ctx, newCm, metav1.CreateOptions{})
				if createErr != nil {
					log.Printf("ERROR: Failed to create ConfigMap '%s': %v", configMapName, createErr)
					return createErr
				}
				log.Printf("Successfully created ConfigMap '%s'", configMapName)
				return nil
			}
			log.Printf("ERROR: Failed to get ConfigMap '%s': %v", configMapName, err)
			return err
		}

		if cm.Data != nil && cm.Data[configMapKey] == content {
			log.Printf("ConfigMap '%s' content for key '%s' is unchanged. Skipping update.", configMapName, configMapKey)
			return nil
		}

		log.Printf("ConfigMap '%s' content needs update for key '%s'.", configMapName, configMapKey)
		if cm.Data == nil {
			cm.Data = make(map[string]string)
		}
		cm.Data[configMapKey] = content
		_, updateErr := cmClient.Update(ctx, cm, metav1.UpdateOptions{})
		if updateErr != nil {
			log.Printf("ERROR: Failed to update ConfigMap '%s' (will retry on conflict): %v", configMapName, updateErr)
		} else {
			log.Printf("Successfully updated ConfigMap '%s'", configMapName)
		}
		return updateErr
	})

	if retryErr != nil {
		return fmt.Errorf("failed to apply ConfigMap changes for '%s' after retries: %w", configMapName, retryErr)
	}

	return nil
}

func runController() {
	cfg := loadConfiguration()

	ticker := time.NewTicker(cfg.PollInterval)
	defer ticker.Stop()

	log.Println("Performing initial configuration fetch...")
	processConfiguration(cfg)

	for range ticker.C {
		processConfiguration(cfg)
	}
}

func processConfiguration(cfg *ControllerConfig) {
	newConfig, err := fetchConfig(cfg)
	if err != nil {
		log.Printf("ERROR: Failed to fetch or parse configuration: %v", err)
		return
	}

	if currentConfig != nil && reflect.DeepEqual(newConfig, currentConfig) {
		log.Println("Configuration hasn't changed. No action needed.")
		// Still run symlink reconciliation periodically even if config hasn't changed
		// to catch manual changes or filesystem inconsistencies.
		err = manageSymlinks(newConfig.Symlinks, cfg)
		if err != nil {
			log.Printf("ERROR: Failed during periodic symlink reconciliation: %v", err)
		}
		return
	}

	log.Println("Configuration change detected. Applying updates...")

	rightsContent, err := generateRightsFileContent(newConfig.Rights)
	if err != nil {
		log.Printf("ERROR: Failed to generate rights file content: %v", err)
	} else {
		err = writeToFile(cfg.RightsFilePath, rightsContent)
		if err != nil {
			log.Printf("ERROR: Failed to write rights file to %s: %v", cfg.RightsFilePath, err)
		}

		if cfg.IsInKubernetes && cfg.RightsConfigMapName != "" {
			ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
			defer cancel()
			err = writeRightsToConfigMap(ctx, cfg, rightsContent)
			if err != nil {
				log.Printf("ERROR: Failed to write rights to ConfigMap %s/%s: %v", cfg.RightsConfigMapNamespace, cfg.RightsConfigMapName, err)
			}
		}
	}

	err = manageSymlinks(newConfig.Symlinks, cfg)
	if err != nil {
		log.Printf("ERROR: Failed during symlink processing: %v", err)
	}

	log.Println("Configuration update applied.")
	currentConfig = newConfig
}
